### ISSUE TITLE
Edit-Posts

### ISSUE THREAD

**Issue by BurnsD** [BurnsD/Ice-cream-store-blog#15]
Receiving Error 500 From when attempting to Edit post:
---------------------------------------------------------------------------------------------------------------------------------------------------
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.format_url (C:\Users\dusti\Desktop\projects\ice-cream\utils\helpers.js:9:10)
    at Object.wrapper (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:13:110)
    at main (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
    at ret (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
    at ret (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:519:21)
    at ExpressHandlebars._renderTemplate (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\express-handlebars\dist\express-handlebars.js:324:16)
    at ExpressHandlebars.<anonymous> (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\express-handlebars\dist\express-handlebars.js:240:37)
    at step (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\express-handlebars\dist\express-handlebars.js:49:23)
    at Object.next (C:\Users\dusti\Desktop\projects\ice-cream\node_modules\express-handlebars\dist\express-handlebars.js:30:53)

---------------------------------------------------------------------------------------------------------------------------------------------------

Unsure where within dashboard-routes.js line 45-83 this is causing an issue or if something is not matching within Handlebars

**Comment by BurnsD** [comment]
Brad has fixed the error and all code should be functioning properly
